baseURL = "https://example.com"
languageCode = "en-us"
title = "Archie"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	
	# Custom CSS
	customcss = ["css/intro.css"]
	
	# Intro section
	showIntro = true
	introPhoto = "/profile.jpg"
	introTitle = "Hi, I'm [Your Name]"
	introText = "Welcome to my personal website. I'm a [your role/profession] passionate about [your interests]. Here you'll find my thoughts, projects, and experiences."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
